Create schema IF NOT EXISTS TESTSC AUTHORIZATION sa;

DROP TABLE IF EXISTS TESTSC.TCUSTOMER;
DROP TABLE IF EXISTS TESTSC.BLOG;

SET SCHEMA TESTSC;
CREATE TABLE IF NOT EXISTS TCUSTOMER (
       OBJ_ID INTEGER AUTO_INCREMENT NOT NULL,
       USER_ID VARCHAR(50) NOT NULL,
       USER_NAME VARCHAR(50) NOT NULL,
       EMAIL VARCHAR(255) NOT NULL,
       CREATE_TIME TIMESTAMP NOT NULL,
       CONSTRAINT PK_CUST PRIMARY KEY(OBJ_ID)
);
CREATE TABLE IF NOT EXISTS BLOG (
      OBJ_ID INTEGER AUTO_INCREMENT NOT NULL,
      BLOG_ID VARCHAR(50) NOT NULL,
      BLOG_HEADLINE VARCHAR(50) NOT NULL,
      BLOG_OWNER VARCHAR(50) NOT NULL,
      CONTENT VARCHAR(255) NOT NULL,
      CREATE_TIME TIMESTAMP NOT NULL,
      UPDATE_TIME TIMESTAMP NOT NULL,
      CONSTRAINT PK_BLOG PRIMARY KEY(OBJ_ID)
);

CREATE TABLE IF NOT EXISTS BLOG (
    DATESEQ VARCHAR(10) NOT NULL,
    DATENUM INT NOT NULL ,
    CONSTRAINT PK_SEQ PRIMARY KEY (DATESEQ)
);


INSERT INTO TCUSTOMER VALUES (
default ,'22666666','casuser','casuser@google.com',CURRENT_TIMESTAMP
);